export const calendarContent = [
    "Learn about the Christkind",
    "Discover Swiss Christmas Markets",
    "Try a recipe for Swiss cookies",
    "Learn about the art of crafting handmade Swiss Christmas cards",
    "Explore the tradition of Advent wreaths in Switzerland",
    "Learn about the significance of candles in Swiss Christmas celebrations",
    "Discover the history of Santa Claus in Swiss culture",
    "Explore the custom of exchanging gifts on St. Nicholas Day",
    "Try a traditional Swiss hot chocolate recipe",
    "Learn about the Swiss tradition of Samichlaus and Schmutzli",
    "Explore the festive decorations in Swiss homes during Christmas",
    "Discover the folklore of Christmas in different Swiss regions",
    "Try a recipe for raclette, a popular Swiss dish during the holidays",
    "Learn about the unique Swiss Christmas tree traditions",
    "Explore the Christmas customs of the Italian-speaking region of Switzerland",
    "Discover the French influence on Christmas celebrations in Switzerland",
    "Try a recipe for Basel-style Läckerli, a Swiss gingerbread cookie",
    "Learn about the winter sports traditions in the Swiss Alps",
    "Explore the craftsmanship of Swiss Christmas ornaments",
    "Discover the customs of celebrating Christmas in the Romansh-speaking region",
    "Try a recipe for Swiss chocolate truffles",
    "Learn about the Swiss tradition of singing Christmas carols",
    "Explore the festive atmosphere of Christmas markets in Zurich",
    "Discover the joy of Swiss Christmas caroling and community gatherings",
    "Merry Christmas! Reflect on the rich tapestry of Swiss Christmas traditions and share your favorite moments."
];
